farmmarket/farmmarket/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mail.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

farmmarket/mail/urls.py
from django.urls import path, include

from . import views


app_name = 'mail'

urlpatterns = [
    path('', views.index, name='index'),
    path('order_paid/', views.order_paid, name='order_paid'),
    path(
        'registration_email/',
        views.registration_email,
        name='registration_email'
    )
]

farmmarket/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}My Site{% endblock %}</title>
</head>
<body>
    <header>
        <h1>{% block heading %}My Site{% endblock %}</h1>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

farmmarket/templates/index.html
<style>
    .button {
      background-color: #4CAF50;
      border: none;
      color: white;
      padding: 15px 32px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      font-size: 16px;
      margin: 4px 2px;
      cursor: pointer;
    }
</style>
<button class="button" onclick="location.href='{% url 'mail:order_paid' %}'">Button 1</button>
<button class="button" onclick="location.href='{% url 'mail:registration_email' %}'">Button 2</button>
<button class="button" onclick="location.href='{% url 'mail:order_paid' %}'">Button 3</button>
<button class="button" onclick="location.href='{% url 'mail:order_paid' %}'">Button 4</button>